### ISSUE TITLE
Implement DAC calibration in new acquisition pipeline.

### ISSUE THREAD

**Issue by GeriG966** [CodethinkLabs/bloodlight-firmware#35]
Implement the DAC calibration procedure in the datasheet.

**Comment by kplus** [comment]
It turns out we only used DAC3/4 in Rev2, and these 2 DACs don't support output buffer which is what calibration based on. So basically we don't need DAC calibration for our use case, thus close this issue. Following is the IRC conversation regarding this:

<pre>
10:02 < terry> I have impletemented the DAC calibration algorithm, but have some questions: 1. is there a different libopencm3 branch I should use for DAC? why the API looks different in bloodlight's dac 
               module? like dac_enable in bloodlight passed in dac base and dac channel mask, but in libopencm3, it only takes channel mask?
10:02 < terry> 2. it seems dac3/4 are chosen in current config, but those have no output buffer, so calibration won't take any affect, is this set up correct?
10:02 < terry> 3. any idea how to test dac calibration?
10:03 < flatmush> 1. The DAC implementation has to be different because we have multiple DAC's, I've been given permission by karlp to rewrite libopencm3's DAC API so it'll likely be very similar to what we're 
                  using now
10:03 < tlsa> cool
10:03 < tlsa> we should be able to move to upstream libopencm3 once that's merged
10:03 < terry> ok, so for the general dac apis, is there a branch I should use?
10:04 < flatmush> 2. Not read into it much, but yeah I think some of the DACs are internal only for opamp-offset. If the calibration is only calibrating against an output buffer to be used externally then maybe 
                  it's not needed? Would seem weird that can't calibrate internally, but idl
10:04 < flatmush> 3. Not really, I'd just assume that going through the motions in the datasheet will make our results marginally more accurate, depending on if it's used internally
10:04 < flatmush> could print out calib values, they should always be the same or very close to factory settings unless you heat the device up a lot (or cool it down)
10:05 < terry> at 22.3 table 179, it says dac3/4 has no output buffer, and 22.4.13 says The calibration is only valid when the DAC channelx is operating with buffer enabled
10:05 < flatmush> ah, then we might not need DAC calibration because we use all DAC's in the same way
10:05 < flatmush> so if one of them is working without a buffer, they probably all are
10:06 < flatmush> I didn't read into it more than seeing it was there to do like we did for ADC, sounds like the task is done with the result that we don't need to calibrate DAC?
10:06 < terry> output buffer is default on(it there is one), but the ones we choose dac3/4 has no such thing...
10:06 < flatmush> ah
10:07 < flatmush> have we tested the use of DAC3/DAC4?
10:07 < terry> so, do you think I still keep the dac calibration impletmentation there? even not used, or just get rid of it?
10:07 < terry> as with current setup, we can't even print the register values to check
10:08 < tlsa> https://gitlab.codethink.co.uk/co054/internal/-/wikis/standup/2020-12-16
10:08 < terry> not yet, I just blingly added the code to do calibration within the placeholder function. 
10:08 < terry> s/blingly/blindly
10:08 < flatmush> so just checking, on rev 2 when we use PD1 (most heavily tested) we use DAC3
10:09 < flatmush> maybe there's a different patch to disable the output buffer to make DAC usage consistent?
10:09 < flatmush> or we could put calibration in and hope it makes a difference when buffering is used (potentially it should)
10:10 < flatmush> wait, it looks like we only ever use DAC3 and DAC4 for OPAMPs
10:10 < flatmush> so we must never used buffer
10:11 < flatmush> I guess a paste of this conversation is enough to close the issue, it's good that you looked into it
</pre>
