### ISSUE TITLE
Optimize flash patterns

### ISSUE THREAD

**Issue by GeriG966** [CodethinkLabs/bloodlight-firmware#44]

**Comment by kplus** [comment]
Just as a record.

We found the flash pattern might randomly got doubled duration when the frequency is approaching the limit(ex. 500Hz with 512 oversampling for 7 sources and 8 LED channels) on Revision 1, but the firmware won't fail out nor warn the user. We suspect it was because the CPU missed interrupt when it's close to the limitation, so some led_loop was skipped which results a doubled duration.

This symptom is not shown on Revision 2, as it's uses hardware oversampling which significantly reduced the CPU load, and the maximum frequency for ADC will be reached before the CPU gets to its limitation.

We don't have plan to optimize this unless it shows affects on further revisions(>=2).

**Comment by kplus** [comment]
In current flash mode, we flash the chosen LEDs in a fixed sequence and sample them interspersely, so compare with continuously mode, the maxmium frequency allowed for flash mode will be inversely proportional to number of LEDs enabled. A typical maximum value will be: 2760Hz with 512 oversample and 2 LEDs enabled, or 1380Hz with 512 oversample and 4 LEDs enabled, etc

Reflective/transmissive mode doesn't impact the configurations, and there is a roughly 6-10us delay for SPI transmission
![rev2-spi-5-7f-1244-delay](https://user-images.githubusercontent.com/10830030/98166017-b731cf80-1ede-11eb-8d9d-a6ed6c917230.png)
which is about 1-2 CPU cycles, and it shouldn't affect the whole sampling period.

**Comment by kplus** [comment]
It seems there is no further issue with flash pattern now, so close it
